language: python

python:
  - "3.9"

services:
  - docker

install: skip

script:
  - bash ./deploy.sh sartography/cr-connect-python-base

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
